# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba0536253af9b2677cdb81a8cfddf17949774cd255d8fdf72f40f2450ffc9970366e9d7594ca26a48e8b526f7173aa62108e8e2b0b427efc23c9d7c057011a0c

test:
  secret_key_base: 86296c5f6f2b512f3ff63c2ff23c1c08a5a199349e94f226436c70860adcded4879505b8920b9e91ef8d22c8035cbeee63ae4a1df0fb468f09ad2eb473281689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
