# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f536404392273cb889902d24ec6cbc11e2134c0258750cadc2710b8e8fb49c97523765b5b1ec304e4600afb9706d534252e6ff18622467035c3663107682c05

test:
  secret_key_base: efcad30e35fb1931c9731be912f93f545bd55e5098fa869d0eafbba6198252d01a392905f90511b43416e9817330019deac2f210de82a3b0ed56c93f0e9c06d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
